import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useBatch } from "@/contexts/batch-context";

const roles = [{ icon: "translate", title: "المترجم", text: "يستورد الصفحات ويعتمد النص النظيف." }, { icon: "fact-check", title: "المراجع", text: "يتحقق من الحواف والألوان قبل القبول." }, { icon: "format-paint", title: "المنسق", text: "يستلم الصفحات الجاهزة لإضافة الترجمة." }];
export default function TeamScreen() { const { project, completedCount } = useBatch(); return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={s.page}><View style={s.top}><View><Text style={s.eyebrow}>TEAM WORKSPACE</Text><Text style={s.title}>مساحة الفريق</Text></View><View style={s.teamIcon}><MaterialIcons name="groups" size={24} color="#071019" /></View></View><View style={s.hero}><Text style={s.heroOverline}>المشروع النشط</Text><Text style={s.heroTitle}>{project.name}</Text><Text style={s.heroText}>{completedCount.toLocaleString("ar")} صفحة جاهزة الآن للمراجعة أو التنسيق داخل فريقك.</Text><View style={s.flow}><Flow icon="translate" text="ترجمة" active /><Flow icon="fact-check" text="مراجعة" active={completedCount > 0} /><Flow icon="format-paint" text="تنسيق" /></View></View><Text style={s.section}>أدوار مسار النشر</Text>{roles.map((role) => <View key={role.title} style={s.role}><View style={s.roleIcon}><MaterialIcons name={role.icon as never} size={21} color="#F8FAFC" /></View><View style={{ flex: 1 }}><Text style={s.roleTitle}>{role.title}</Text><Text style={s.roleText}>{role.text}</Text></View></View>)}<View style={s.note}><MaterialIcons name="lock-outline" size={18} color="#AFC8FF" /><Text style={s.noteText}>هذه النسخة تحفظ مشاريع الاستوديو على الجهاز. مشاركة الأعضاء والمراجعات المتزامنة تحتاج ربط حسابات الفريق عند تفعيل مساحة العمل السحابية.</Text></View><Pressable style={({ pressed }) => [s.button, pressed && { opacity: .8 }]}><MaterialIcons name="person-add" size={20} color="#071019" /><Text style={s.buttonText}>تجهيز دعوات الفريق</Text></Pressable></ScrollView></ScreenContainer>; }
function Flow({ icon, text, active }: { icon: string; text: string; active?: boolean }) { return <View style={s.flowItem}><View style={[s.flowIcon, active && s.flowActive]}><MaterialIcons name={icon as never} size={17} color={active ? "#071019" : "#9FACBC"} /></View><Text style={s.flowText}>{text}</Text></View>; }
const s = StyleSheet.create({ page: { padding: 20, paddingBottom: 40, gap: 11 }, top: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, eyebrow: { color: "#8795A8", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, title: { color: "#F8FAFC", fontSize: 28, fontWeight: "900", textAlign: "right", marginTop: 4 }, teamIcon: { width: 46, height: 46, borderRadius: 16, backgroundColor: "#F8FAFC", alignItems: "center", justifyContent: "center" }, hero: { backgroundColor: "#151B26", borderColor: "#2A3443", borderWidth: 1, borderRadius: 24, padding: 18, marginTop: 8 }, heroOverline: { color: "#A8C8FF", fontSize: 10, fontWeight: "900", textAlign: "right" }, heroTitle: { color: "#FFFFFF", fontSize: 20, fontWeight: "900", textAlign: "right", marginTop: 5 }, heroText: { color: "#A6B3C2", fontSize: 12, lineHeight: 19, textAlign: "right", marginTop: 7 }, flow: { flexDirection: "row-reverse", justifyContent: "space-between", marginTop: 18 }, flowItem: { alignItems: "center", gap: 6 }, flowIcon: { width: 35, height: 35, borderRadius: 12, backgroundColor: "#252F3F", justifyContent: "center", alignItems: "center" }, flowActive: { backgroundColor: "#9AC6FF" }, flowText: { color: "#A7B4C3", fontSize: 10, fontWeight: "800" }, section: { color: "#F8FAFC", fontSize: 16, fontWeight: "900", textAlign: "right", marginTop: 12 }, role: { flexDirection: "row-reverse", gap: 12, alignItems: "center", backgroundColor: "#10151E", borderColor: "#202937", borderWidth: 1, borderRadius: 18, padding: 14 }, roleIcon: { width: 41, height: 41, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#27384F" }, roleTitle: { color: "#FFFFFF", fontWeight: "900", fontSize: 14, textAlign: "right" }, roleText: { color: "#96A5B6", fontSize: 11, lineHeight: 17, textAlign: "right", marginTop: 3 }, note: { flexDirection: "row-reverse", gap: 8, backgroundColor: "#142039", borderRadius: 16, padding: 13, marginTop: 9 }, noteText: { flex: 1, color: "#ABC2E3", textAlign: "right", fontSize: 11, lineHeight: 18 }, button: { height: 52, borderRadius: 16, backgroundColor: "#F8FAFC", flexDirection: "row-reverse", justifyContent: "center", alignItems: "center", gap: 8, marginTop: 4 }, buttonText: { color: "#071019", fontWeight: "900", fontSize: 14 } });
